CREATE TABLE IF NOT EXISTS `appointments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tracking_code` VARCHAR(50) NOT NULL,
  `authority` VARCHAR(100) DEFAULT NULL,
  `ref_id` VARCHAR(100) DEFAULT NULL,
  `full_name` VARCHAR(150) NOT NULL,
  `mobile` VARCHAR(20) NOT NULL,
  `appointment_date` DATE NOT NULL,
  `appointment_time` TIME NOT NULL,
  `amount` INT NOT NULL DEFAULT 0,
  `description` TEXT DEFAULT NULL,
  `payment_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0=pending,1=failed,2=paid',
  `admin_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0=pending,1=approved,2=rejected,3=cancelled',
  `gateway_response` TEXT DEFAULT NULL,
  `admin_note` TEXT DEFAULT NULL,
  `paid_at` DATETIME DEFAULT NULL,
  `approved_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_tracking_code` (`tracking_code`),
  KEY `idx_appointment_slot` (`appointment_date`, `appointment_time`),
  KEY `idx_payment_admin_status` (`payment_status`, `admin_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
